spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ems?createIfNotExist=true&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update